### PR TITLE
Bump dependencies (micrometer/tracing, spring-boot, central-dogma)

### PR DESCRIPTION
**Pull request by mauhiz**
Why : to keep dependencies recent

Note: there's no related code change as the changes are supposed to be binary compatible

### CODE REVIEW

**Review by ocadaruma — APPROVED** [review]
Thank you always!

Please give me some time till merge. We have to make some fix to continuous-benchmark code first

**Comment by Yang-33** [comment]
How about adding [renovate](https://docs.renovatebot.com/) in this repository to update dependencies automatically? 
Since renovate supports to ignore updates for specific libraries, it's not a problem if there are libraries that haven't been updated for a reason.

For example, line/line-bot-sdk-java uses renovate to update dependencies automatically. https://github.com/line/line-bot-sdk-java/blob/master/renovate.json

**Comment by mauhiz** [comment]
Sounds good, +1 for renovate!
It works poorly with builds that are too heavily customized but this should be okay here

**Comment by ocadaruma** [comment]
@Yang-33 Thank you for the suggestion. Sounds good. Let us consider that.

**Review by ocadaruma — APPROVED** [review]

**Pull request merged**
